export const DOCTOR_SCHEDULE_DATA = {
  doctor_id: "doc100293456",
  fullname: "Hoàng Trần",
  doctorSchedules: [
    {
      department_id: "departmentid",
      schedule_id: "scheduleid1",
      department_name: "Khoa tai mũi họng",
      dayOfweek: "Monday",
      startTime: "8:00",
      endTime: "9:00",
    },
    {
      department_id: "departmentid",
      schedule_id: "scheduleid1",
      department_name: "Khoa tai mũi họng",
      dayOfweek: "Monday",
      startTime: "9:00",
      endTime: "10:00",
    },
    {
      department_id: "departmentid",
      schedule_id: "scheduleid1",
      department_name: "Khoa tai mũi họng",
      dayOfweek: "Monday",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      department_id: "departmentid",
      schedule_id: "scheduleid1",
      department_name: "Khoa tai mũi họng",
      dayOfweek: "Monday",
      startTime: "13:00",
      endTime: "14:00",
    },
    {
      department_id: "departmentid",
      schedule_id: "scheduleid1",
      department_name: "Khoa tai mũi họng",
      dayOfweek: "Monday",
      startTime: "14:00",
      endTime: "15:00",
    },
    {
      department_id: "departmentid",
      schedule_id: "scheduleid1",
      department_name: "Khoa tai mũi họng",
      dayOfweek: "Monday",
      startTime: "15:00",
      endTime: "16:00",
    },
    {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Tuesday",
        startTime: "8:00",
        endTime: "9:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Tuesday",
        startTime: "9:00",
        endTime: "10:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Tuesday",
        startTime: "10:00",
        endTime: "11:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Tuesday",
        startTime: "14:00",
        endTime: "15:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Tuesday",
        startTime: "15:00",
        endTime: "16:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Wednesday",
        startTime: "8:00",
        endTime: "9:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Wednesday",
        startTime: "9:00",
        endTime: "10:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Wednesday",
        startTime: "10:00",
        endTime: "11:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Wednesday",
        startTime: "13:00",
        endTime: "14:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Wednesday",
        startTime: "14:00",
        endTime: "15:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Wednesday",
        startTime: "15:00",
        endTime: "16:00",
      },

      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Thursday",
        startTime: "10:00",
        endTime: "11:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Thursday",
        startTime: "13:00",
        endTime: "14:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Thursday",
        startTime: "14:00",
        endTime: "15:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Thursday",
        startTime: "15:00",
        endTime: "16:00",
      },

      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Friday",
        startTime: "8:00",
        endTime: "9:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Friday",
        startTime: "9:00",
        endTime: "10:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Friday",
        startTime: "10:00",
        endTime: "11:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Friday",
        startTime: "14:00",
        endTime: "15:00",
      },
      {
        department_id: "departmentid",
        schedule_id: "scheduleid1",
        department_name: "Khoa tai mũi họng",
        dayOfweek: "Friday",
        startTime: "15:00",
        endTime: "16:00",
      },
  ],
};
