export const DOCTOR = {
  doctor_id: "doc100293456",
  department_id: "dep28347311a",
  fullname: "Hoàng Trần",
  Gender: "Male",
  department_name: "Khoa tai mũi họng",
  DOB: "date_of_birth",
  phone_number: "phone_number",
  appointments: [
    {
      appointment_id: "appointmentid1",
      date: "date",
      Day_of_week: "day_of_week",
      patient_name: "patient_name",
      startTime: "start_time",
      endTime: "end_time",
      status: "status",
    },
    {
      appointment_id: "appointmentid2",
      date: "date",
      Day_of_week: "day_of_week",
      patient_name: "patient_name",
      startTime: "start_time",
      endTime: "end_time",
      status: "status",
    },
    {
      appointment_id: "appointmentid3",
      date: "date",
      Day_of_week: "day_of_week",
      patient_name: "patient_name",
      startTime: "start_time",
      endTime: "end_time",
      status: "status",
    },
    {
      appointment_id: "appointmentid4",
      date: "date",
      Day_of_week: "day_of_week",
      patient_name: "patient_name",
      startTime: "start_time",
      endTime: "end_time",
      status: "status",
    },
  ],
};
