export const DOCTOR = {
  doctor_id: "doc100293456",
  department_id: "dep28347311a",
  fullname: "Hoàng Trần",
  Gender: "Male",
  department_name: "Khoa tai mũi họng",
  DOB: "date_of_birth",
  phone_number: "phone_number",
  appointments: [
    {
      appointment_id: "appointmentid1",
      date: "18 March 24",
      Day_of_week: "tuesday",
      patient_name: "Tiến Gié",
      startTime: "9:00",
      endTime: "10:00",
      status: "finished",
    },
    {
      appointment_id: "appointmentid2",
      date: "19 March 24",
      Day_of_week: "wednesday",
      patient_name: "Hoàng Sơn",
      startTime: "7:00",
      endTime: "8:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid3",
      date: "19 March 24",
      Day_of_week: "wednesday",
      patient_name: "Huy Ngô",
      startTime: "8:00",
      endTime: "9:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid4",
      date: "19 March 24",
      Day_of_week: "wednesday",
      patient_name: "Thomas Johnson",
      startTime: "14:00",
      endTime: "15:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid5",
      date: "19 March 24",
      Day_of_week: "wednesday",
      patient_name: "Quý ngài ẩn danh",
      startTime: "15:00",
      endTime: "16:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid6",
      date: "20 March 24",
      Day_of_week: "thursday",
      patient_name: "lão Hạc",
      startTime: "9:00",
      endTime: "10:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid7",
      date: "20 March 24",
      Day_of_week: "thursday",
      patient_name: "NoName",
      startTime: "14:00",
      endTime: "15:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid8",
      date: "21 March 24",
      Day_of_week: "tuesday",
      patient_name: "Ẩn Danh",
      startTime: "14:00",
      endTime: "15:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid9",
      date: "22 March 24",
      Day_of_week: "tuesday",
      patient_name: "Ẩn Danh",
      startTime: "14:00",
      endTime: "15:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid10",
      date: "20 March 24",
      Day_of_week: "tuesday",
      patient_name: "Ẩn Danh",
      startTime: "14:00",
      endTime: "15:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid11",
      date: "21 March 24",
      Day_of_week: "tuesday",
      patient_name: "Ẩn Danh",
      startTime: "14:00",
      endTime: "15:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid12",
      date: "22 March 24",
      Day_of_week: "tuesday",
      patient_name: "Ẩn Danh",
      startTime: "14:00",
      endTime: "15:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid13",
      date: "23 March 24",
      Day_of_week: "tuesday",
      patient_name: "Ẩn Danh",
      startTime: "14:00",
      endTime: "15:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid14",
      date: "25 March 24",
      Day_of_week: "tuesday",
      patient_name: "Ẩn Danh",
      startTime: "14:00",
      endTime: "15:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid15",
      date: "24 March 24",
      Day_of_week: "tuesday",
      patient_name: "Ẩn Danh",
      startTime: "14:00",
      endTime: "15:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid16",
      date: "25 March 24",
      Day_of_week: "tuesday",
      patient_name: "Ẩn Danh",
      startTime: "14:00",
      endTime: "15:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid17",
      date: "21 March 24",
      Day_of_week: "tuesday",
      patient_name: "Ẩn Danh",
      startTime: "14:00",
      endTime: "15:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid18",
      date: "19 March 24",
      Day_of_week: "tuesday",
      patient_name: "Chú Hề",
      startTime: "14:00",
      endTime: "15:00",
      status: "pending",
    },
    {
      appointment_id: "appointmentid19",
      date: "17 March 24",
      Day_of_week: "tuesday",
      patient_name: "Chú Hề",
      startTime: "14:00",
      endTime: "15:00",
      status: "pending",
    },
  ],
};
